# Generated by Django 5.1.4 on 2025-02-04 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
