# Generated by Django 5.1.4 on 2025-02-04 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_delete_donor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='district',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pin',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='place',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='post',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('donor', 'Donor'), ('beneficiary', 'Beneficiary')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
