# Generated by Django 5.1.4 on 2025-02-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_remove_customuser_role_customuser_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(max_length=255),
        ),
    ]
