# Generated by Django 5.1.4 on 2025-02-05 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0006_alter_customuser_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonor',
            fields=[
                ('donor_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('blood_group', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('place', models.CharField(max_length=255)),
                ('post', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('event_status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=50)),
                ('sponsor_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('volunteer_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('place', models.CharField(max_length=255)),
                ('post', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=255)),
                ('availability', models.BooleanField(default=True)),
                ('assigned_task', models.TextField(blank=True, null=True)),
                ('proof', models.FileField(blank=True, null=True, upload_to='volunteer_proofs/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiarySupport',
            fields=[
                ('beneficiary_id', models.AutoField(primary_key=True, serialize=False)),
                ('emergency_type', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('proof', models.FileField(blank=True, null=True, upload_to='beneficiary_proofs/')),
                ('emergency_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('donation_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('donation_details', models.TextField()),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comments', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_quantity', models.IntegerField()),
                ('allocated_quantity', models.IntegerField()),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.beneficiarysupport')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.donation')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=50)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.donation')),
            ],
        ),
        migrations.CreateModel(
            name='PalliativeCare',
            fields=[
                ('palliative_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('needs', models.TextField()),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='FieldData',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('post', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('details', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed')], max_length=50)),
                ('proof', models.FileField(blank=True, null=True, upload_to='field_data_proofs/')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.volunteer')),
            ],
        ),
    ]
