# Generated by Django 5.1.4 on 2025-02-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0009_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='palliativecare',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='sponsor_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
