# Generated by Django 5.1.4 on 2025-02-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0010_palliativecare_details_staff_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
