# Generated by Django 5.1.4 on 2025-02-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0011_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
