# Generated by Django 5.1.4 on 2025-02-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0012_alter_staff_full_name_alter_staff_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='availability',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='availability_date',
            field=models.DateField(default=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='volunteering_in',
            field=models.CharField(choices=[('HWH', 'Hospital Without Hunger'), ('EGA', 'Essential Grocery Assistance'), ('CHC', 'Comprehensive Home Care'), ('BAS', 'Beneficiary Aid & Support'), ('PCP', 'Palliative Care Program'), ('GC', 'Guidance & Counseling')], default=True, max_length=20),
        ),
    ]
