# Generated by Django 5.1.4 on 2025-02-09 11:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0013_remove_volunteer_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='availability_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
