# Generated by Django 5.1.4 on 2025-02-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0015_add_missing_fields'),
    ]

    operations = [
    ]
