# Generated by Django 5.1.4 on 2025-02-11 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0018_alter_donation_options_alter_donation_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='target_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Enter the target budget amount for sponsorship', max_digits=10),
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsorship_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='charity.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
