# Generated by Django 5.1.4 on 2025-02-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0019_event_target_budget_sponsorship'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('donation_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='donation_products/')),
                ('category', models.CharField(choices=[('medical', 'Medical Expenses'), ('meals', 'Nourish the Needy'), ('grocery', 'Essential Grocery Assistance'), ('home', 'Comprehensive Home Care')], max_length=20)),
            ],
        ),
    ]
