# Generated by Django 5.1.4 on 2025-02-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0020_donationproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Payment transaction ID.', max_length=100, null=True),
        ),
    ]
