# Generated by Django 5.1.4 on 2025-02-15 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0021_donation_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='transaction_id',
        ),
    ]
