# Generated by Django 5.1.4 on 2025-02-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0023_volunteer_user_alter_volunteer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fielddata',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10),
        ),
    ]
