# Generated by Django 5.1.4 on 2025-02-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0024_fielddata_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='fielddata',
            name='phone',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
