# Generated by Django 5.1.4 on 2025-02-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0025_fielddata_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddata',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
