# Generated by Django 5.1.4 on 2025-02-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0026_alter_fielddata_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('monetary', 'Monetary'), ('medical', 'Medical Expenses'), ('meals', 'Nourish the Needy'), ('grocery', 'Essential Grocery Assistance'), ('home', 'Comprehensive Home Care'), ('other', 'Other Donations')], help_text='Select the type of donation.', max_length=100),
        ),
    ]
