# Generated by Django 5.1.4 on 2025-02-27 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0027_alter_donation_donation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the amount for monetary donations or the estimated value for in-kind donations.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='allocated_quantity',
            field=models.IntegerField(default=0, help_text='Quantity already allocated'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='beneficiary',
            field=models.ForeignKey(blank=True, help_text='Beneficiary allocated to (if any)', null=True, on_delete=django.db.models.deletion.CASCADE, to='charity.beneficiarysupport'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='total_quantity',
            field=models.IntegerField(help_text='Total quantity available in inventory'),
        ),
    ]
