# Generated by Django 5.1.4 on 2025-02-27 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0028_alter_donation_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palliativecare',
            name='details',
        ),
    ]
