# Generated by Django 5.1.4 on 2025-03-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0030_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiarysupport',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarysupport',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarysupport',
            name='beneficiary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarysupport',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarysupport',
            name='beneficiary_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarysupport',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarysupport',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarysupport',
            name='pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarysupport',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarysupport',
            name='post',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarysupport',
            name='relationship',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
