# Generated by Django 5.1.4 on 2025-03-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0031_beneficiarysupport_address_beneficiarysupport_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiarysupport',
            name='custom_other_donation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarysupport',
            name='other_donation_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
