# Generated by Django 5.1.4 on 2025-03-03 03:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0035_alter_donation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='allocated_quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='inventory_id',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='total_quantity',
        ),
        migrations.AddField(
            model_name='inventory',
            name='allocated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='allocated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='charity.beneficiarysupport'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='date_received',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='item_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beneficiarysupport',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=50),
        ),
    ]
