# Generated by Django 5.1.4 on 2025-03-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0036_remove_inventory_allocated_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiarysupport',
            name='allocation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
