# Generated by Django 5.1.4 on 2025-03-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0037_beneficiarysupport_allocation_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalliativePatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('contactNumber', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('medicalCondition', models.TextField()),
                ('additionalDetails', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
