# Generated by Django 5.1.4 on 2025-03-07 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0038_palliativepatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='palliativepatient',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='charity.volunteer'),
        ),
    ]
