# Generated by Django 5.1.4 on 2025-03-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0040_beneficiarysupport_completion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiarysupport',
            name='approval_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
