# Generated by Django 5.1.4 on 2025-03-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0041_beneficiarysupport_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationproduct',
            name='category',
            field=models.CharField(choices=[('medical', 'Medical Expenses'), ('meals', 'Nourish the Needy'), ('grocery', 'Essential Grocery Assistance'), ('home', 'Comprehensive Home Care'), ('hospital_beds', 'Hospital Beds'), ('wheel_chairs', 'Wheel Chairs'), ('walkers', 'Walkers'), ('hygiene_products', 'Hygiene Products'), ('nutritious_food', 'Nutritious Food'), ('other', 'Other Donations')], max_length=20),
        ),
    ]
