# Generated by Django 5.1.4 on 2025-03-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0042_alter_donationproduct_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fielddata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Beneficiary Full Name'),
        ),
    ]
