# Generated by Django 5.1.4 on 2025-03-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0045_beneficiarysupport_account_holder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='volunteering_in',
            field=models.CharField(choices=[('Hospital Without Hunger', 'Hospital Without Hunger'), ('Essential Grocery Assistance', 'Essential Grocery Assistance'), ('Comprehensive Home Care', 'Comprehensive Home Care'), ('Beneficiary Aid & Support', 'Beneficiary Aid & Support'), ('Palliative Care Program', 'Palliative Care Program'), ('Guidance & Counseling', 'Guidance & Counseling'), ('Others', 'Others')], default='Others', max_length=30),
        ),
    ]
