# Generated by Django 5.1.4 on 2025-03-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0046_alter_volunteer_volunteering_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Coordinator', 'Coordinator')], max_length=100),
        ),
    ]
