# Generated by Django 5.1.4 on 2025-03-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0049_alter_volunteer_volunteering_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('monetary', 'Monetary'), ('Medical Expenses', 'Medical Expenses'), ('Nourish the Needy', 'Nourish the Needy'), ('Essential Grocery Assistance', 'Essential Grocery Assistance'), ('Comprehensive Home Care', 'Comprehensive Home Care'), ('Other Donations', 'Other Donations')], help_text='Select the type of donation.', max_length=100),
        ),
    ]
