# Generated by Django 5.1.4 on 2025-03-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0050_alter_donation_donation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='allocated',
        ),
        migrations.AddField(
            model_name='inventory',
            name='allocated_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
