# Generated by Django 5.1.4 on 2025-03-27 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0052_remove_inventory_allocated_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldArea',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Unassigned', 'Unassigned'), ('Assigned', 'Assigned'), ('Completed', 'Completed')], default='Unassigned', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('completion_status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('field_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.fieldarea')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.volunteer')),
            ],
        ),
    ]
