# Generated by Django 5.1.4 on 2025-03-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0053_fieldarea_volunteerassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerassignment',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
