# Generated by Django 5.1.4 on 2025-03-27 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0054_volunteerassignment_completion_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_details', models.TextField()),
                ('completion_date', models.DateField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.volunteer')),
            ],
        ),
        migrations.DeleteModel(
            name='VolunteerAssignment',
        ),
    ]
