# Generated by Django 5.1.4 on 2025-03-27 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0055_fieldassignment_delete_volunteerassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charity.palliativepatient'),
        ),
    ]
