# Generated by Django 5.1.4 on 2025-03-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0057_rename_assignment_details_fieldassignment_responsibilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='group',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
