# Generated by Django 5.1.4 on 2025-03-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0058_notification_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
