# Generated by Django 5.1.4 on 2025-03-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0059_remove_notification_notification_id_notification_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='group',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
