# Generated by Django 5.1.4 on 2025-03-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0060_remove_notification_group_alter_notification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
