# Generated by Django 5.1.4 on 2025-03-28 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0062_notification_group_alter_notification_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='group',
        ),
    ]
