# Generated by Django 5.1.4 on 2025-03-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0063_remove_notification_group'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='notification',
        #     old_name='id',
        #     new_name='notification_id',
        # ),
        migrations.AddField(
            model_name='notification',
            name='group',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
