# Generated by Django 5.1.4 on 2025-03-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0064_rename_id_notification_notification_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationproduct',
            name='category',
            field=models.CharField(choices=[('Medical Expenses', 'Medical Expenses'), ('Nourish the Needy', 'Nourish the Needy'), ('grocery', 'Essential Grocery Assistance'), ('Essential Grocery Assistance', 'Comprehensive Home Care'), ('Hospital Beds', 'Hospital Beds'), ('Wheel Chairs', 'Wheel Chairs'), ('Walkers', 'Walkers'), ('Hygiene Products', 'Hygiene Products'), ('Nutritious Food', 'Nutritious Food'), ('Other Donations', 'Other Donations')], max_length=80),
        ),
    ]
