# Generated by Django 5.1.4 on 2025-03-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0065_alter_donationproduct_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='date_time',
            new_name='created_at',
        ),
        # migrations.RemoveField(
        #     model_name='notification',
        #     name='group',
        # ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
