# Generated by Django 5.1.4 on 2025-03-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0067_notif_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('donor', 'Donor'), ('beneficiary', 'Beneficiary'), ('volunteer', 'Volunteer')], max_length=20),
        ),
    ]
