# Generated by Django 5.1.4 on 2025-03-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0070_alter_fielddata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notif',
            name='unread',
            field=models.BooleanField(default=True),
        ),
    ]
