# Generated by Django 5.1.4 on 2025-03-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0071_notif_unread'),
    ]

    operations = [
        migrations.AddField(
            model_name='palliativepatient',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
