# Generated by Django 5.1.4 on 2025-03-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0072_palliativepatient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldassignment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
