# Generated by Django 5.1.4 on 2025-03-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0073_fieldassignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldassignment',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
