# Generated by Django 5.1.4 on 2025-05-06 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0075_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
