# Generated by Django 5.1.4 on 2025-05-06 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0077_delete_fieldarea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
