# Generated by Django 5.1.4 on 2025-05-06 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0078_delete_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PalliativeCare',
        ),
    ]
