# Generated by Django 5.1.4 on 2025-05-06 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0079_delete_palliativecare'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FieldAssignment',
            new_name='FieldArea',
        ),
    ]
